
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 27 00:54:52 CET 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 29;
  public static final int CONST = 6;
  public static final int ASTERISK = 17;
  public static final int SLASH = 18;
  public static final int NUMCONST = 40;
  public static final int NOTEQUAL = 21;
  public static final int LPAREN = 34;
  public static final int GREATER = 22;
  public static final int CONTINUE = 14;
  public static final int LESS = 24;
  public static final int MINUS = 16;
  public static final int RPAREN = 35;
  public static final int SEMICOLON = 31;
  public static final int AND = 26;
  public static final int LESSEQUAL = 25;
  public static final int OR = 27;
  public static final int COMMA = 32;
  public static final int CLASS = 4;
  public static final int EQUALEQUAL = 20;
  public static final int PLUS = 15;
  public static final int IF = 7;
  public static final int DOT = 33;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 30;
  public static final int RETURN = 11;
  public static final int EQUAL = 28;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int PERCENT = 19;
  public static final int BREAK = 3;
  public static final int VOID = 12;
  public static final int GREATEREQUAL = 23;
  public static final int LBRACE = 38;
  public static final int ELSE = 5;
  public static final int LSQUARE = 36;
  public static final int READ = 10;
  public static final int CHARCONST = 41;
  public static final int RSQUARE = 37;
  public static final int RBRACE = 39;
  public static final int BOOLCONST = 42;
  public static final int EXTENDS = 13;
  public static final int PRINT = 9;
  public static final int IDENTIFIER = 43;
}

