
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 27 16:47:08 CET 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 30;
  public static final int ASTERISK = 18;
  public static final int SLASH = 19;
  public static final int NUMCONST = 41;
  public static final int NOTEQUAL = 22;
  public static final int LPAREN = 35;
  public static final int GREATER = 23;
  public static final int CONTINUE = 15;
  public static final int LESS = 25;
  public static final int MINUS = 17;
  public static final int RPAREN = 36;
  public static final int SEMICOLON = 32;
  public static final int AND = 27;
  public static final int LESSEQUAL = 26;
  public static final int OR = 28;
  public static final int COMMA = 33;
  public static final int CLASS = 4;
  public static final int EQUALEQUAL = 21;
  public static final int PLUS = 16;
  public static final int IF = 6;
  public static final int DOT = 34;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 31;
  public static final int RETURN = 10;
  public static final int EQUAL = 29;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int PERCENT = 20;
  public static final int BREAK = 3;
  public static final int VOID = 11;
  public static final int GREATEREQUAL = 24;
  public static final int LBRACE = 39;
  public static final int ELSE = 5;
  public static final int LSQUARE = 37;
  public static final int READ = 9;
  public static final int CHARCONST = 42;
  public static final int RSQUARE = 38;
  public static final int WHILE = 13;
  public static final int RBRACE = 40;
  public static final int BOOLCONST = 43;
  public static final int EXTENDS = 14;
  public static final int PRINT = 8;
  public static final int DO = 12;
  public static final int IDENTIFIER = 44;
}

